### ISSUE TITLE
komment: problems with test.tm, error creating comments

### ISSUE THREAD

**Issue by mdbenito** [texmacs/tm-forge#9]
**UPDATE**: I'm not sure this is valid. It's quite weird. Probably due to an installation problem (after copying the files, tools->update plugin resulted in `in procedure scm-error in expression (scm-error (quote misc-error) #f ...): no code for module (komments)`". After a restart things seem to work, except for the test.tm file in the repo

Runnig SVN Texmacs r13414.

Tags in test.tm are not displayed correctly. Additionally, creating a comment with Ctrl+m results in a tag being created but in the console one sees:

```
TeXmacs] Guile error: ((wrong-type-arg widget-texmacs-input Wrong type argument in position ~A: ~S (1 (document #f)) ((document #f))))
Backtrace:
(...)
(...)debug.scm:231:19: In procedure widget-texmacs-input in expression (apply throw err):
(...)debug.scm:231:19: Wrong type argument in position 1: (document #f)
```

**Comment by mdbenito** [comment]
Ok, I've deinstalled the plugin, cleared the cache, rerun with --setup (again), and the problem is no longer there => closing (sorry!)

**Comment by slowphil** [comment]
Hi Miguel. I somehow missed your issue till now, sorry. From what you experienced, I guess there should be an advice in the README about clearing the cache in case of problems.

Can I get the permission to directly edit the README, without going through a PR? That could be handy to maintain my contributed code, or to fix small issues I could find here and there. For instance there is a broken link to the pdf in fontawsome/README.md (docs instead of doc in the url).

Totally unrelated : many icons are missing in Github's preview of the pdf (at least in my browser)
![image](https://user-images.githubusercontent.com/16419323/118391284-cf27a000-b633-11eb-83c5-c383000bd6fa.png)
but I'm afraid there is not much one can do about that.

**Comment by mgubi** [comment]
@slowphil I reinvented you in the texmacs organisation. I think if you accept you will be able to modify all the repositories.
